# Generated by Django 6.0.7 on 2026-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='matric_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
